version: "3"
services:
  jenkins:
    container_name: my-jenkins
    image: elissa71/plantshedv2
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /c/Users/notju/Jenkins-data/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins
networks:
  jenkins: